title: Ankit kumar jha
description: Data Scientist|Data Analyst|Buisness Analyst|Data Engineer
  [![View on GitHub](https://img.shields.io/badge/GitHub-View_on_GitHub-Red?logo=GitHub)](https://github.com/ANKITJHA1601/Lead-Scoring-Case-study)|
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/ANKITJHA1601/">GitHub</a>

google_analytics:
theme: jekyll-theme-dinky
