title: Ankit kumar jha
description: Data Scientist|Data Analyst|Buisness Analyst|Data Engineer<br><br>
  
  <a class="buttons" href="https://www.linkedin.com/in/sajan-kedia-b06a6821/"><img src="https://cdn.icon-icons.com/icons2/2428/PNG/512/linkedin_black_logo_icon_147114.png" alt="LinkedIn" width="50px" height="700px"></a>
|
  

 

google_analytics:
theme: jekyll-theme-dinky
