title: Ankit kumar jha
description: Data Scientist|Data Analyst|Buisness Analyst|Data Engineer<br>
  
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |<br>
  [![LinkedIn](https://img.shields.io/badge/-LinkedIn-blue?style=flat-square&logo=Linkedin&logoColor=white&link=your-linkedin-url)](linkedin.com/in/ankit-jha-98084918a)

 

google_analytics:
theme: jekyll-theme-dinky
