title: Ankit kumar jha
description: Data Scientist | Data Analyst| Buisness Analyst.       



  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/ANKITJHA1601/">GitHub</a>

google_analytics:
theme: jekyll-theme-dinky
