title: Ankit kumar jha
description: Data Scientist|Data Analyst|Buisness Analyst|Data Engineer<br><br>
   <a class="buttons" href="https://www.linkedin.com/in/ankit-jha-98084918a/"><img src="https://raw.githubusercontent.com/ANKITJHA1601/Ankit-Portfolio/master/assets/images/icons8-linkedin-50.png" alt="LinkedIn" width="30px" height="30px"></a> |
   <a class="buttons" href="mail4ankitjha@gmail.com"><img src="https://img.shields.io/badge/-Gmail-red?style=flat&logo=Gmail&logoColor=white" alt="Gmail"></a>

  
  

  

 

google_analytics:
theme: jekyll-theme-dinky
